"""Generate Kitaeru's PNG app icons from the vector sources in this folder.

    icon-any.svg       -> icon-192.png, icon-512.png, apple-touch-icon.png (180)
    icon-maskable.svg  -> icon-maskable-512.png (everything inside the 80% safe zone)

The SVGs (and favicon.svg) are generated by docs/brand/build_logos.py, direction B (the carved seal).
They contain only paths, so no font is involved. They are rendered with a headless Chromium browser
(Microsoft Edge or Google Chrome) at 1024 px and downsampled with Pillow for clean edges.

Usage:  python icons/make_icons.py            (needs Pillow and Edge or Chrome installed)
        set KITAERU_BROWSER=path\\to\\chrome.exe to choose the browser.
"""
import os, shutil, subprocess, tempfile
from pathlib import Path
from PIL import Image

HERE = Path(__file__).resolve().parent
RENDER = 1024
JOBS = [('icon-any.svg', [('icon-192.png', 192), ('icon-512.png', 512), ('apple-touch-icon.png', 180)]),
        ('icon-maskable.svg', [('icon-maskable-512.png', 512)])]
CANDIDATES = [
    os.environ.get('KITAERU_BROWSER', ''),
    r'C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe',
    r'C:\Program Files\Microsoft\Edge\Application\msedge.exe',
    r'C:\Program Files\Google\Chrome\Application\chrome.exe',
    '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    '/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge',
    shutil.which('google-chrome') or '', shutil.which('chromium') or '', shutil.which('microsoft-edge') or '',
]


def browser():
    for c in CANDIDATES:
        if c and Path(c).exists():
            return c
    raise SystemExit('No Edge/Chrome found; set KITAERU_BROWSER to a Chromium-based browser.')


def render(svg_path, exe, tmp):
    # A wrapper page pins the SVG to the top-left at exactly RENDER px; the window is larger because
    # headless Chromium enforces a minimum window width, and the result is cropped.
    page = Path(tmp) / 'wrap.html'
    page.write_text(f'<!doctype html><style>html,body{{margin:0;background:#fff}}img{{display:block;width:{RENDER}px;height:{RENDER}px}}</style>'
                    f'<img src="{svg_path.as_uri()}">', encoding='utf-8')
    out = Path(tmp) / 'shot.png'
    subprocess.run([exe, '--headless=new', '--disable-gpu', '--no-first-run', '--hide-scrollbars', '--force-device-scale-factor=1',
                    f'--user-data-dir={Path(tmp) / "profile"}', '--allow-file-access-from-files',
                    f'--window-size={RENDER + 16},{RENDER + 16}', '--virtual-time-budget=1500',
                    f'--screenshot={out}', page.as_uri()], check=True, capture_output=True, timeout=120)
    return Image.open(out).convert('RGB').crop((0, 0, RENDER, RENDER))


def main():
    exe = browser()
    with tempfile.TemporaryDirectory() as tmp:
        for src, outs in JOBS:
            big = render(HERE / src, exe, tmp)
            for name, size in outs:
                big.resize((size, size), Image.LANCZOS).save(HERE / name, optimize=True)
                print(f'{name}  {size}x{size}  from {src}')


if __name__ == '__main__':
    main()
